### ISSUE TITLE
Messages not processed under alarm.

### ISSUE THREAD

**Issue by spinza** [jpbarraca/ParadoxMulti-MQTT#10]
To sort out my needs I kind of wrote my own code to some degree and spotted various improvements to your code and the orgiinal code.

Most important is the handling of message types.  The first byte actually conveys both status info and the command.  The high nibble of the first byte is the command, the low nibble has some state info.  

Hence your code fails to process messages when the state changes in some cases.  Most specifically under alarm conditions.   I wanted to see which zones are opened after alarm but those messages were not processed.

Thought I'd pay back by raising this here.

You can see what i do here which "explains" what I mean:
https://github.com/spinza/paradox_mqtt/blob/master/paradox.py#L941

Your code needs to change here:
https://github.com/jpbarraca/ParadoxMulti-MQTT/blob/master/ParadoxMulti-MQTT.py#L545

It does not cover alarm states.

Details on low nibble here:
https://github.com/spinza/paradox_mqtt/blob/master/paradox.py#L644

**Comment by spinza** [comment]
Also the software connected bit allows you to spot when logged out and then relogin to module if needs be.

**Comment by jpbarraca** [comment]
That code was not written by me, and AFAIK it was written when the structure was not known. You are correct and I will need to change the entire way of operation. However, only recently I found the proper protocol (https://dl.dropboxusercontent.com/content_link_zip/58HAIfcVzEaHx9xKZDKkFfrTGo23hi4KkhAQRlrWNIYBdMUUC6cfAYwLVqAs3OSC/file?_download_id=54991074634511185737701198686980866135455269141414918931173291217&_notify_domain=www.dropbox.com&dl=1)

My plan is to build a proper parser just for debug and after I'm sure that all messages are properly parsed, evolve into a new structure.

**Comment by spinza** [comment]
Great that you have the protocol.  Do you mind sharing that?  You perhaps need a different kind of link as the link above is not working.

**Comment by jpbarraca** [comment]
https://www.dropbox.com/sh/dztab03vwdmw8ya/AABNac4VglpRPQMMHVh5myCea?dl=0

With this information messages can probably be parsed/built appropriately, which will imply many changes to the existing codebase.
