### ISSUE TITLE
Additional Zone States

### ISSUE THREAD

**Issue by spinza** [jpbarraca/ParadoxMulti-MQTT#11]
Could track more zone states eg:
* Fire alarm
* Supervision failure (wireless connection problems)
* Trouble
* Tamper 

See https://github.com/spinza/paradox_mqtt/blob/master/paradox.py#L909

Probably ways to get these from keepalive responses also. Which I haven't attempted.

**Comment by jpbarraca** [comment]
The answer is yes and no.
Would you like to join efforts in a new codebase that handles the messages appropriatelly?
I already have a preliminary prototype and it much more maintainable.

**Comment by jpbarraca** [comment]
here: https://github.com/jpbarraca/pai
