### ISSUE TITLE
Micro controller 

### ISSUE THREAD

**Issue by maragelis** [jpbarraca/ParadoxMulti-MQTT#2]
I would like to ask if there is any chance this could be implemented on a arduino or lets say a ESP8266.
I have got to read all serial data and send it to mqtt using wifi chip esp8266. I just cant seem to get the control part.

**Comment by jpbarraca** [comment]
It should be easy to port it to a ESP8266, and maybe an arduino with network connection. However, you can use a PI Zero Wireless without any changes.

**Comment by maragelis** [comment]
Ok got it working on a esp8266 thanks
