### ISSUE TITLE
Passthrough Issues

### ISSUE THREAD

**Issue by spinza** [jpbarraca/ParadoxMulti-MQTT#6]
Not managing to get passthrough working from babyware:
![image](https://user-images.githubusercontent.com/3501598/38274511-3fcd96ce-378f-11e8-817d-54b7f1ebd8a0.png)

Config:
![image](https://user-images.githubusercontent.com/3501598/38274467-25de1978-378f-11e8-8591-5e8133fc9455.png)

Server:
```
2018-04-03 22:31:38,319 MQTT Message: Paradox/Control/State PASSTHROUGH                                  
2018-04-03 22:31:38,320 Switching to Passthrough mode                                                    
2018-04-03 22:31:45,048 Invalid message
2018-04-03 22:31:45,048 37 <-  70 00 10 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 80
2018-04-03 22:31:45,144 Opening Serial port: /dev/ttyUSB0
2018-04-03 22:31:45,151 Serial port open!
2018-04-03 22:31:45,152 Passthrough: Waiting for client
2018-04-03 22:31:45,254 Passthrough: Client connected: ('192.168.2.11', 61273)
[23, <socket._socketobject object at 0x7efde473b8a0>]
-> aa04000309f000000001eeeeeeee6e10958aaef4ed88c9c153ddb3fac77c0efd
-> aa04000309f000000001eeeeeeee6e10958aaef4ed88c9c153ddb3fac77c0efd
-> aa04000309f000000001eeeeeeee6e10958aaef4ed88c9c153ddb3fac77c0efd
-> aa04000309f000000001eeeeeeee6e10958aaef4ed88c9c153ddb3fac77c0efd
-> aa00000309f400000001eeeeeeee7305
-> aa00000309f400000001eeeeeeee7305
-> aa00000309f400000001eeeeeeee7305
-> aa00000309f400000001eeeeeeee7305
-> aa00000309f400000001eeeeeeee7305
```

**Comment by jpbarraca** [comment]
I tested Passthrough using a TCP to Serial bridge and not with babyware.
Can you sniff a full interaction with a real module?

**Comment by jpbarraca** [comment]
Correct.
Supporting a direct connection from Babyware would be great, but I cannot decode the message format :/

**Comment by spinza** [comment]
Don't know much but reading the PyMQTTIP150 code there is the additional 16 byte header followed by the 37 byte serial message

Can't you almost ignore the 16byte header and go with the rest. Just think the login bit may be different. 

I guess you'd still need to figure out how it responds. As Babyware might not br happy with incorrect responses.

**Comment by jpbarraca** [comment]
The messages I capture have 32 or 16 bytes. But maybe they are related to the login and are not supposed to be delivered to the panel.

**Comment by spinza** [comment]
Yeah sorry guess is all I can do. My IP150 is v4+ and doesn't support this at all.

**Comment by spinza** [comment]
Another idea is to connect the Paradox Mqtt ip150 script to yours. Might be easier to get that working first before jumping straight to Babyware.
