### ISSUE TITLE
Suport SP7000

### ISSUE THREAD

**Issue by radebebek** [jpbarraca/ParadoxMulti-MQTT#9]
Is it this plugin support SP7000 alarm centrals ?
Alarm_Model = ParadoxMG5050  change with Alarm_Model = **ParadoxSP7000**
Alarm_Registry_Map = ParadoxMG5050 change with Alarm_Registry_Map = **ParadoxSP7000**    
Alarm_Event_Map = ParadoxMG5050  change with Alarm_Event_Map = **ParadoxSP7000**      
Zone_Amount = 32

**Comment by jpbarraca** [comment]
I have no idea... :(
Can you test without any modification to the code?

**Comment by radebebek** [comment]
Yes, I set only my ip addres for paradox ip150, code pin xxxx, and pasword.
Succesful conect to alarm system, but I have some error.
Link for log: Error : 
http://prntscr.com/j17e63

**Comment by jpbarraca** [comment]
New code here: https://github.com/jpbarraca/pai
